#FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime
FROM python:3.8

RUN apt update && apt install -y git build-essential
#RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --upgrade torch torchvision torchaudio

RUN git clone https://github.com/neonbjb/tortoise-tts.git

WORKDIR /tortoise-tts

#install dependencies
#RUN sed  -i 's/scipy==0.10.1/scipy==1.10.1/g' requirements.txt && \
#pip install $(cat requirements.txt | grep numpy) && \
#pip install llvmlite==0.31.0 && \
#pip install $(cat requirements.txt | grep numba) && \
#pip install -r requirements.txt

RUN sed  -i 's/scipy==0.10.1/scipy==1.10.1/g' requirements.txt && \
pip install -r requirements.txt

RUN python setup.py install

#download models
RUN python -c "from tortoise.api import TextToSpeech as tts; tts()"

#install and launch GUI
RUN pip install gradio==3.20.1 && pip install numpy==1.20.3
WORKDIR /workspace
COPY ./app.py ./app.py

EXPOSE 7860

CMD [ "python", "app.py" ]

